### ISSUE TITLE
NexthopGroup member change is not supported

### ISSUE THREAD

**Issue by yue-fred-gao** [sonic-net/sonic-platform-vpp#115]
When running test_vxlan_ecmp sonic-mgmt test, I found nexthop group member change is not supported. This can happen in many situations. For this particular test case, a nexthop group member can be added or removed dynamically triggered by bfd state change. When nexthop group member changed, we need to delete the routes and reprogram them if they point to the nexthop group.

**Comment by linqingxuan** [comment]
Are you referring to the changes in the underlay nexthopGroup?

**Comment by yue-fred-gao** [comment]
Yes. Let's say we have route_entry points to nexthopgroup with 2 members. It can happen that a new member added/deleted to the nexthop group via nexthopgroup_member create/delete but not update to the route_entry. We need to handle the create/delete event by finding all route_entry points to the nexthopgroup and reprogram the routes. I have implemented the change and will create a PR shortly.

**Comment by linqingxuan** [comment]
Thank you very much for your modifications. I have recently started testing Sonic VM with VPP and am in the process of deploying VM pass-through with Mellanox Technologies MT27800 Family [ConnectX-5] network cards.

**Comment by yue-fred-gao** [comment]
Fixed by PR #120
