### ISSUE TITLE
build process is trying to pull ipmitool version no longer available, updategraph.service not generated

### ISSUE THREAD

**Issue by Krishnamoney** [sonic-net/sonic-platform-vpp#117]
Trying to build the repository failed with error trying to pull outdated/non existing ipmitool version and requires manual edits to point this to the latest available version for build to complete.
vppcfg service requires updategraph.service which was not present in the vm image.

**Comment by yue-fred-gao** [comment]
We are in the process to push vpp to sonic-buildimage. Once that is done, we will be able to build sonic-vpp directly from sonic-buildimage, as any other platform.

For vppcfg service, I might have broken it during this activity. Here are some basic questions: what is vppcfg service? How is it used? I can't find any doc about it.

**Comment by Krishnamoney** [comment]
We were trying to bring up the VM image and seems like vpp docker image is started by systemctl service of linux, and this  failed to start the vppcfg service with error since dependent service update graph is not installed/present.

**Comment by Krishnamoney** [comment]
Any timelines  available for proposed vpp merge push to sonic build image?

**Comment by yue-fred-gao** [comment]
> We were trying to bring up the VM image and seems like vpp docker image is started by systemctl service of linux, and this service failed to start (the vppcfg service ) with error since dependent service update graph is not installed/present.

In which git commit id do you see this? In the VM image, I don't think we need vppcfg service.

**Comment by yue-fred-gao** [comment]
> Any timelines available for proposed vpp merge push to sonic build image?

I think by the end of Oct this should be done. The sonic side of change has been approved.

**Comment by Krishnamoney** [comment]
> > We were trying to bring up the VM image and seems like vpp docker image is started by systemctl service of linux, and this service failed to start (the vppcfg service ) with error since dependent service update graph is not installed/present.
> 
> In which git commit id do you see this? In the VM image, I don't think we need vppcfg service.

I was using latest tip of the tree. I thought we might need some systemctl service which brings up vpp container once VM is booted and looking for the services present in the VM.

**Comment by linqingxuan** [comment]
> > We were trying to bring up the VM image and seems like vpp docker image is started by systemctl service of linux, and this service failed to start (the vppcfg service ) with error since dependent service update graph is not installed/present.
> 
> In which git commit id do you see this? In the VM image, I don't think we need vppcfg service.

I think this initialization interface related project is used to read data from redis to initialize the interface. Later, I think it can be expanded in some ways that are not issued from sai.

**Comment by yue-fred-gao** [comment]
I have changed interface initialization with PR #106. Interface will be automatically created in the first boot so it behaves the same way as other platforms. There is no need to run sonic_vpp_cfg.sh then reboot to bring up data ports. It might be less flexible than before because it is taking all interfaces except eth0 as data ports. If we do need different port configuration, we may introduce other hwsku.

**Comment by Krishnamoney** [comment]
We also need to fix make sonic_vm build failure. ipmitool_1.8.19-4 is no longer available and should be updated to get ipmitool_1.8.19-7 instead (sonic-platform-vpp/build/sonic-buildimage/rules/ipmitool.mk) 

get_url_version https://deb.debian.org/debian/pool/main/i/ipmitool/ipmitool_1.8.19-4.dsc failed
dget: curl ipmitool_1.8.19-4.dsc https://deb.debian.org/debian/pool/main/i/ipmitool/ipmitool_1.8.19-4.dsc failed
make[1]: *** [Makefile:9: /sonic/target/debs/bookworm/ipmitool_1.8.19-4_amd64.deb] Error 1
make[1]: Leaving directory '/sonic/src/ipmitool'
[  FAIL LOG END  ] [ target/debs/bookworm/ipmitool_1.8.19-4_amd64.deb ]
make: *** [slave.mk:735: target/debs/bookworm/ipmitool_1.8.19-4_amd64.deb] Error 1
make: *** Waiting for unfinished jobs....
[ 01 ] [ target/debs/bookworm/linux-headers-6.1.0-11-2-common_6.1.38-4_all.deb ]

**Comment by yue-fred-gao** [comment]
This is not from sonic-vpp but upstream sonic. It is because that version of debian package has been removed from the debian.org. You can try adding MIRROR_SNAPSHOT=y to the make command. We could patch it after download sonic but I see it has little value. When vpp is built from sonic-buildimage, this won't be a problem.

**Comment by linqingxuan** [comment]
This actually needs to be observed. The new code I pulled yesterday also had the same problem, but the upstream sonic has been changed for a month, and we still have problems when we rebuild it.

**Comment by yue-fred-gao** [comment]
This is because the current sonic-vpp build process is pegged to a certain version of sonic: https://github.com/sonic-net/sonic-platform-vpp/blob/main/sonic-vpp-setup.sh#L30. That's the issue PR #123 is going to fix.

**Comment by yue-fred-gao** [comment]
@linqingxuan, if you have time, can you please review PR #123? I can't assign you as reviewer but you can still review and add your comments

**Comment by linqingxuan** [comment]
OK, I will review this PR [#123  ]https://github.com/sonic-net/sonic-platform-vpp/pull/123)carefully.

**Comment by Krishnamoney** [comment]
When will sonic-platform-vpp become a submodule of sonic-buildimage?

**Comment by yue-fred-gao** [comment]
I am not sure at the moment. The PR has opened for 2 weeks: https://github.com/sonic-net/sonic-buildimage/pull/20841.

**Comment by Krishnamoney** [comment]
Sure - since https://github.com/sonic-net/sonic-buildimage/pull/20841 is going to address this issue, I am closing this ticket.
