### ISSUE TITLE
Inquiry Regarding Sonic Version Compatibility with SAI

### ISSUE THREAD

**Issue by linqingxuan** [sonic-net/sonic-platform-vpp#121]
I found that the version of the SAI I compiled does not meet the minimum requirements. Do you have this error? Can you show me your SAI version?Or is there something wrong with me?
``` log
 Oct 12 10:53:15.446246 sonic NOTICE syncd#syncd#syncd: :- isVeryFirstRun: First Run: True
2024 Oct 12 10:53:15.446510 sonic NOTICE syncd#syncd#syncd: :- profileGetValue: SAI_VPP_SWITCH_TYPE: NULL
2024 Oct 12 10:53:15.446744 sonic ERR syncd#syncd#syncd: :- apiInitialize: failed to obtain service method table value: SAI_VPP_SWITCH_TYPE
2024 Oct 12 10:53:15.446991 sonic ERR syncd#syncd#syncd: :- queryApiVersion: virtual sai_status_t saivpp::Sai::queryApiVersion(sai_api_version_t*): SAI API not initialized
2024 Oct 12 10:53:15.447245 sonic NOTICE syncd#syncd#syncd: :- apiInitialize: SAI API vendor version: 0
2024 Oct 12 10:53:15.447481 sonic NOTICE syncd#syncd#syncd: :- apiInitialize: SAI API min version: 10900
2024 Oct 12 10:53:15.447703 sonic NOTICE syncd#syncd#syncd: :- apiInitialize: SAI API headers version: 11400
2024 Oct 12 10:53:15.447990 sonic ERR syncd#syncd#syncd: :- apiInitialize: SAI implementation API version 0 or SAI headers API version 11400 does not meet minimum version requirements, min version required: 10900
```

**Comment by linqingxuan** [comment]
Oh, maybe it's not initialized somewhere.

**Comment by DanielaMurin** [comment]
According to your log, 1.14.0 is the latest version of your build.

You'll need to implement the following function (found in saiversion.h):

sai_status_t sai_query_api_version(
        _Out_ sai_api_version_t *version) {

    *version = 11400; // hard-coded for simplicity's sake, you can change it
    return SAI_STATUS_SUCCESS;
}

There are also probably a few more functions that need implementation, such as: 
sai_query_attribute_enum_values_capability
sai_query_stats_capability
sai_query_object_stage
...

You should see them in the fail log if the compilation is not successful.

Just as a heads up, SAI has recently updated to version 1.15.0. (https://github.com/opencomputeproject/SAI/pull/2088)

**Comment by yue-fred-gao** [comment]
It seems like SAI is not properly initialized. I don't see this problem in latest build. Are you running latest?

**Comment by linqingxuan** [comment]
2 02:07:15.010386 sonic DEBUG syncd#syncd#syncd: :> syncd_main: enter
2024 Oct 22 02:07:15.013075 sonic NOTICE syncd#syncd#syncd: :- initialize: initializeing metadata log function
2024 Oct 22 02:07:15.013075 sonic WARNING syncd#syncd#syncd: :- parseCommandLine: param -s is depreacated, use -z
2024 Oct 22 02:07:15.014011 sonic NOTICE syncd#syncd#syncd: :- Syncd: sairedis git revision a988dd1b, SAI git revision: be52377
2024 Oct 22 02:07:15.014547 sonic NOTICE syncd#syncd#syncd: :- threadFunction: starting timer watchdog thread
2024 Oct 22 02:07:15.014660 sonic ERR syncd#syncd#syncd: :- logSet: virtual sai_status_t saivpp::Sai::logSet(sai_api_t, sai_log_level_t): api not initialized
2024 Oct 22 02:07:15.038580 sonic ERR syncd#syncd#syncd: message repeated 64 times: [ :- logSet: virtual sai_status_t saivpp::Sai::logSet(sai_api_t, sai_log_level_t): api not initialized]
2024 Oct 22 02:07:15.038645 sonic NOTICE syncd#syncd#syncd: :- Syncd: command line:  EnableDiagShell=NO EnableTempView=YES DisableExitSleep=NO EnableUnittests=NO EnableConsistencyCheck=NO EnableSyncMode=YES RedisCommunicationMode=redis_async EnableSaiBulkSuport=NO StartType=cold ProfileMapFile=/usr/share/sonic/hwsku/sai.profile GlobalContext=0 ContextConfig= BreakConfig= WatchdogWarnTimeSpan=30000000
2024 Oct 22 02:07:15.038687 sonic NOTICE syncd#syncd#syncd: :- loadFromFile: no context config specified, will load default context config
2024 Oct 22 02:07:15.038729 sonic NOTICE syncd#syncd#syncd: :- insert: added switch: idx 0, hwinfo ''
2024 Oct 22 02:07:15.038763 sonic WARNING syncd#syncd#syncd: :- Syncd: enable sync mode is deprecated, please use communication mode, FORCING redis sync mode
2024 Oct 22 02:07:15.041257 sonic NOTICE syncd#syncd#syncd: :- RedisSelectableChannel: opened redis channel
2024 Oct 22 02:07:15.044355 sonic NOTICE syncd#syncd#syncd: :- isVeryFirstRun: First Run: True
2024 Oct 22 02:07:15.044479 sonic NOTICE syncd#syncd#syncd: :- profileGetValue: SAI_VPP_SWITCH_TYPE: NULL
2024 Oct 22 02:07:15.044479 sonic ERR syncd#syncd#syncd: :- apiInitialize: failed to obtain service method table value: SAI_VPP_SWITCH_TYPE
2024 Oct 22 02:07:15.044479 sonic ERR syncd#syncd#syncd: :- queryApiVersion: virtual sai_status_t saivpp::Sai::queryApiVersion(sai_api_version_t*): SAI API not initialized
2024 Oct 22 02:07:15.044479 sonic NOTICE syncd#syncd#syncd: :- apiInitialize: SAI API vendor version: 0
2024 Oct 22 02:07:15.046491 sonic NOTICE syncd#syncd#syncd: :- apiInitialize: SAI API min version: 10900
2024 Oct 22 02:07:15.046491 sonic NOTICE syncd#syncd#syncd: :- apiInitialize: SAI API headers version: 11400
2024 Oct 22 02:07:15.046491 sonic ERR syncd#syncd#syncd: :- apiInitialize: SAI implementation API version 0 or SAI headers API version 11400 does not meet minimum version requirements, min version required: 10900
2024 Oct 22 02:07:15.046491 sonic ERR syncd#syncd#syncd: :- Syncd: FATAL: failed to sai_api_initialize: SAI_STATUS_FAILURE
2024 Oct 22 02:07:15.362763 sonic INFO coredump_gen_handler.py[30250]: Per Container rate_limit_interval for syncd has not passed. Techsupport Invocation is skipped
2024 Oct 22 02:07:16.261804 sonic INFO syncd#syncd#supervisord 2024-10-22 02:07:16,261 WARN exited: syncd (terminated by SIGABRT (core dumped); not expected)
2024 Oct 22 02:07:16.972128 sonic ERR syncd#syncd#vpp[26]: exec: empty file `/tmp/vppQVIffR.cfg'
2024 Oct 22 02:07:17.265833 sonic INFO syncd#syncd#supervisor-proc-exit-listener: Process 'syncd' exited unexpectedly. Terminating supervisor 'syncd'
2024 Oct 22 02:07:17.265833 sonic NOTICE syncd#syncd#supervisor-proc-exit-listener: :- publish: EVENT_PUBLISHED: {"sonic-events-host:process-exited-unexpectedly":{"ctr_name":"syncd","process_name":"syncd","timestamp":"2024-10-22T02:07:17.265712Z"}}
2024 Oct 22 02:07:17.267802 sonic INFO syncd#syncd#supervisord 2024-10-22 02:07:17,266 WARN received SIGTERM indicating exit request
2024 Oct 22 02:07:17.267802 sonic INFO syncd#syncd#supervisord 2024-10-22 02:07:17,267 INFO waiting for supervisor-proc-exit-listener, rsyslogd, vpp_init.sh to die
2024 Oct 22 02:07:17.644081 sonic INFO swss#supervisord 2024-10-22 02:07:17,643 INFO waiting for supervisor-proc-exit-listener, rsyslogd, portsyncd to die
2024 Oct 22 02:07:17.644784 sonic INFO swss#supervisord 2024-10-22 02:07:17,644 WARN stopped: portsyncd (terminated by SIGTERM)
2024 Oct 22 02:07:18.934652 sonic NOTICE root: Unlocking /tmp/swss-syncd-lock (10) from swss service
2024 Oct 22 02:07:19.014658 sonic INFO systemd[1]: Stopping syncd.service - syncd service...

**Comment by linqingxuan** [comment]
I recently recompiled and found that it could not be compiled

**Comment by linqingxuan** [comment]
The submitted code is missing definitions @yue-fred-gao  like vl_api_bfd_udp_add_v2_reply_t,vl_api_want_bfd_events_v2_reply_t

**Comment by yue-fred-gao** [comment]
Yes, we are aware of the issue. A fix will be committed in a day or two. In the mean time, you can apply below diff. You need to delete *vpp*.debs from build/sonic-buildimage/target/debs/bookworm to rebuild vpp.

diff --git a/platform/vpp/vppbld/Makefile b/platform/vpp/vppbld/Makefile
index 86892a3..c2f1119 100644
--- a/platform/vpp/vppbld/Makefile
+++ b/platform/vpp/vppbld/Makefile
@@ -15,7 +15,8 @@
 SHELL = /bin/bash
 .SHELLFLAGS += -e
 
-VPP_URL = https://gerrit.fd.io/r/vpp
+VPP_URL = https://github.com/abdbaig/vpp.git
+VPP_BRANCH = 21_days_old
 VPP_SHA =
 VPP_LAG = 21
 USER = $(shell id -un)
@@ -68,7 +69,7 @@ build_vpp:
 .PHONY: repo_clone
 repo_clone:
        rm -rf $(VPP_REPO_DIR)
-       git clone $(VPP_URL) $(VPP_REPO_DIR)
+       git clone -b $(VPP_BRANCH) $(VPP_URL) $(VPP_REPO_DIR)
        cp -r $(VPP_CUSTOM_PLUGINS_DIR)/* $(VPP_REPO_DIR)/src/plugins/
        pushd $(VPP_REPO_DIR)
        @VPP_SHA=`git log --until "$(VPP_LAG) days ago" -1 --format="%h"`

**Comment by linqingxuan** [comment]
Ok, thank you very much for your patch
