### ISSUE TITLE
Ping test with noLinuxNl = yes is failing with latest  SONiC VPP image

### ISSUE THREAD

**Issue by nikunjdh** [sonic-net/sonic-platform-vpp#52]
For this latest image, ping test with noLinuxNl = yes is failing.  Ping test works file with noLinuxNl = no. 

Investigation notes from Shashi:

During  loopback creation the vpp returned an error (below).
 
Jun 24 03:37:21.956206 e8eb7f6aa079 NOTICE #syncd: :- asyncOnLinkMsg: received RTM_NEWLINK ifname: Loopback0, ifflags: 0x100c3, ifindex: 6
Jun 24 03:37:21.968178 e8eb7f6aa079 NOTICE #syncd: :- process_interface_loopback: destination_ip:172.16.4.1 interfaceName:Loopback0 isLoopback:1
Jun 24 03:37:21.968203 e8eb7f6aa079 NOTICE #syncd: :- vpp_add_del_lpb_intf_ip_addr: create_loopback_instance interfaceName:loop0 hwif_name:loop0 instance:0
Jun 24 03:37:21.968563 e8eb7f6aa079 INFO #supervisord: syncd msg_handler_internal:588: no handler for msg id 136
Jun 24 03:37:22.061923 e8eb7f6aa079 NOTICE #syncd: :- threadFunction: time span 97 ms for 'create:SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"172.16.4.1/32","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000003"}'
Jun 24 03:37:22.971831 e8eb7f6aa079 ERR #syncd: :- vpp_add_del_lpb_intf_ip_addr: create_loopback_instance returned error
 
Ramesh,
    I think there is no handler registered for CREATE_LOOPBACK_REPLY  however CREATE_LOOPBACK request is made for loopback creation.
 
# vppctl show api message | grep '^136'
136  create_loopback_reply

**Comment by patilshashidhar** [comment]
Fixed by https://github.com/sonic-net/sonic-platform-vpp/pull/53
