### ISSUE TITLE
With latest SONiC-VPP image, T1 Topology bring up fails as snmpd exits quicky after startup

### ISSUE THREAD

**Issue by nikunjdh** [sonic-net/sonic-platform-vpp#69]
With latest VM image built on 8/06 and 8/16, snmpd and snmp-subagent are not running causing T1 topology test validation failure. Initially snmpd is running fine, it fails after configuring minigraph.  (step - ./testbed-cli.sh -t vtestbed.yaml -m veos_vtb deploy-mg vms-kvm-t0 veos_vtb password.txt )

docker exec -it 5996aa230a3c supervisorctl status
containercfgd                    RUNNING   pid 27, uptime 0:17:11
dependent-startup                RUNNING   pid 7, uptime 0:17:14
rsyslogd                         RUNNING   pid 21, uptime 0:17:12
snmp-subagent                    STOPPED   Not started
snmpd                            FATAL     Exited too quickly (process log may have details)
start                            EXITED    Aug 08 12:44 AM
supervisor-proc-exit-listener    RUNNING   pid 8, uptime 0:17:14

Test failure:

E                       Failed: !!!!!!!!!!!!!!!! Pre-test sanity check after recovery failed: !!!!!!!!!!!!!!!!
E                       [
E                           {
E                               "failed": true,
E                               "check_item": "processes",
E                               "host": "vlab-03",
E                               "processes_status": {
E                                   "pmon": {
E                                       "status": true,
E                                       "exited_critical_process": [],
E                                       "running_critical_process": []
E                                   },
E                                   **"snmp": {
E                                       "status": false,
E                                       "exited_critical_process": [
E                                           "snmp-subagent",
E                                           "snmpd"
E                                       ],**
E                                       "running_critical_process": []
E                                   },
E                                   "lldp": {
E                                       "status": true,
E                                       "exited_critical_process": [],
E                                       "running_critical_process": [
E                                           "lldp-syncd",
E                                           "lldpd",
E                                           "lldpmgrd"
E                                       ]
E                                   },

Image: https://engci-maven.cisco.com/artifactory/sonic-vpp-cdn-local/sonic-vpp-vm/2023-08-16/sonic-vpp.img.gz

**Comment by yue-fred-gao** [comment]
not seeing this in the latest build
