### ISSUE TITLE
With latest SONiC-VPP image, all BGP Neighbor are not comming up for T1 Topology

### ISSUE THREAD

**Issue by nikunjdh** [sonic-net/sonic-platform-vpp#70]
With latest VM image built on 8/08 and 8/16, all BGP neighbor are staying in active state, doesn't go to Established state.

Image: https://engci-maven.cisco.com/artifactory/sonic-vpp-cdn-local/sonic-vpp-vm/2023-08-16/sonic-vpp.img.gz

admin@vlab-03:~$ show ip bgp summ

IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 1
RIB entries 1, using 184 bytes of memory
Peers 32, using 23705856 KiB of memory
Peer groups 2, using 128 bytes of memory

Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.1       4  65200          0          0         0      0       0  never      Active          ARISTA01T2
10.0.0.3       4  65200          0          0         0      0       0  never      Active          ARISTA02T2
10.0.0.5       4  65200          0          0         0      0       0  never      Active          ARISTA03T2
10.0.0.7       4  65200          0          0         0      0       0  never      Active          ARISTA04T2
10.0.0.9       4  65200          0          0         0      0       0  never      Active          ARISTA05T2
10.0.0.11      4  65200          0          0         0      0       0  never      Active          ARISTA06T2
10.0.0.13      4  65200          0          0         0      0       0  never      Active          ARISTA07T2
10.0.0.15      4  65200          0          0         0      0       0  never      Active          ARISTA08T2
10.0.0.17      4  65200          0          0         0      0       0  never      Active          ARISTA09T2
10.0.0.19      4  65200          0          0         0      0       0  never      Active          ARISTA10T2
10.0.0.21      4  65200          0          0         0      0       0  never      Active          ARISTA11T2
10.0.0.23      4  65200          0          0         0      0       0  never      Active          ARISTA12T2
10.0.0.25      4  65200          0          0         0      0       0  never      Active          ARISTA13T2
10.0.0.27      4  65200          0          0         0      0       0  never      Active          ARISTA14T2
10.0.0.29      4  65200          0          0         0      0       0  never      Active          ARISTA15T2
10.0.0.31      4  65200          0          0         0      0       0  never      Active          ARISTA16T2
10.0.0.33      4  64001          0          0         0      0       0  never      Active          ARISTA01T0
10.0.0.35      4  64002          0          0         0      0       0  never      Active          ARISTA02T0
10.0.0.37      4  64003          0          0         0      0       0  never      Active          ARISTA03T0
10.0.0.39      4  64004          0          0         0      0       0  never      Connect         ARISTA04T0
10.0.0.41      4  64005          0          0         0      0       0  never      Connect         ARISTA05T0
10.0.0.43      4  64006          0          0         0      0       0  never      Connect         ARISTA06T0
10.0.0.45      4  64007          0          0         0      0       0  never      Active          ARISTA07T0
10.0.0.47      4  64008          0          0         0      0       0  never      Active          ARISTA08T0
10.0.0.49      4  64009          0          0         0      0       0  never      Connect         ARISTA09T0
10.0.0.51      4  64010          0          0         0      0       0  never      Active          ARISTA10T0
10.0.0.53      4  64011          0          0         0      0       0  never      Active          ARISTA11T0
10.0.0.55      4  64012          0          0         0      0       0  never      Active          ARISTA12T0
10.0.0.57      4  64013          0          0         0      0       0  never      Active          ARISTA13T0
10.0.0.59      4  64014          0          0         0      0       0  never      Active          ARISTA14T0
10.0.0.61      4  64015          0          0         0      0       0  never      Active          ARISTA15T0
10.0.0.63      4  64016          0          0         0      0       0  never      Active          ARISTA16T0

Total number of neighbors 32
admin@vlab-03:~$ 

Standard T1 topology, Peer/neighbor device are ceOS Container, they are up and running with all required interfaces configured correctly. When I bring up T1 topology with SONiC-VPP DUT image generated on Aug 6th BGP neighbors are coming up fine. But when I replace SONiC-VPP DUT with image generated on Aug 8th or 16th BGP neighbors are not coming up. So, I am suspecting some issue with SONiC-VPP image instead of Peer/neighbor device. Only delta between Aug6th and Aug8th image is merge of PR#66.

**Comment by yue-fred-gao** [comment]
not seeing this anymore with latest build
