### ISSUE TITLE
Update sonic-buildimage to latest 202311 build

### ISSUE THREAD

**Issue by Giluerre** [sonic-net/sonic-platform-vpp#94]
For the last month, Microsoft updated their package repository, causing some resources to be unavailable during builds. However, these issues have been fixed in the main repository (sonic-buildimage). I suggest updating to the stable branch 202311 of sonic-buildimages.  

~~sonic-sairedis and SAI version shall be preserved to currently working version. As their update should be part of different PR. ~~
EDIT: Leaving the SAI version triggered a domino effect across multiple repositories so I had to slightly change a few line of code in libvpp.

I look forward to a possible discussion.

**Comment by yue-fred-gao** [comment]
already on 20240718 with PR #102
